language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/google-cloud-sdk/

# script: "mvn cobertura:cobertura"
before_install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  # Decrypt gcloud service key
  - openssl aes-256-cbc -K $encrypted_1bf8a0d1cf40_key -iv $encrypted_1bf8a0d1cf40_iv -in client-secret.json.enc -out client-secret.json -d
  - gcloud auth activate-service-account --key-file client-secret.json

install:
  - gcloud config set project blissful-cell-141318

before_script:
  env:
  - TEST=true

after_script:
  env:
  - TEST=false

deploy:
  provider: script
  script: (mvn clean package && exec mvn gcloud:deploy)
  on: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
