language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/google-cloud-sdk/

# script: "mvn cobertura:cobertura -Ptest -Dquiet=true"

before_install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  # Decrypt gcloud service key
  - openssl aes-256-cbc -K $encrypted_1bf8a0d1cf40_key -iv $encrypted_1bf8a0d1cf40_iv -in client-secret.json.enc -out client-secret.json -d
  - gcloud auth activate-service-account --key-file client-secret.json
  - npm config set registry http://registry.npmjs.org/

install:
  - gcloud config set project blissful-cell-141318

script: "mvn -Ptest verify -Dquiet=true"

deploy:
  - provider: script
    skip_cleanup: true
    #attempting to run test with in-memory profile then package without
    script: (mvn clean package -DskipTests && exec mvn gcloud:deploy -DskipTests -Dgcloud.version=staging -Dlog_level=error)
    on: master
  - provider: script
    skip_cleanup: true
    #attempting to run test with in-memory profile then package without
    script: (mvn clean package -DskipTests && exec mvn gcloud:deploy -DskipTests -Dlog_level=error)
    # no_stop_previous_version: true
    on: master

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sauce_connect:
    username: "cloudsrest"
  jwt:
    secure: "w3zPGrQZIBOLnWwPckQcBoMPKXDMZK6bZJLtdTmh+VE6wKRFhaXu+Otbdrdcvos6Z6wfE94nwHMahVmbdnkzYF1fT9xxdyGUZTA7fnaEGI5FXPscsoagY/R+o1SA8lBwTkbqkwKqW6g6qT+hAdvX4CYdmmaQPVENeWNNXHIDDYysN0KpcyYvd14VE+d2o6YXa3QjPP5rF+g7fJ4hpMjMR8K/LovHBebjKy3tBpJECrgi97xfBYtGmXoefwMOdlRkm+V5lXCjt9P263+Syfnezk0CrArnQUlHuSGVEwsa++NJo6Grot7BpVe99KCtq2VoBojaIYS8wNpdrKi6LAybtAQDWaNP0Bt4azZwqOBOgufDXrnvp9EjMDQd9ND2fJsaqOwxFo/+17fQJgahjobAoUhhhJm2BPEguUhsRcri3v4gNr8US6WSc7nu4cXszchuG5WvUd5DBiG8rVMxz1/XE0uTb90wreqCgDwp+dot21WFnZS2aRv6A0OpO1ZjH594xEszP1R2CIbfFf+MlmBrJQyDpE0QE/Y9DHZr6ROge/a1dWfQPb8xay1RpdhXFohV9tgevpPyxUX/Z1HL6uBUe6C1CLnRNntxym2slAMhkKu6nE8lIRrpz8K2Nkx1/Q+VruLdZD0g1e4QpwSQaRU2VuHMhOc/H71dMOAfDVETEXE="
