language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

env:
# Make sure gcloud command is on our PATH
- PATH=$PATH:${HOME}/google-cloud-sdk/bin

before_install:
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi

- gcloud auth activate-service-account --key-file client-secret.json


#before_install:
  # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
  # - openssl aes-256-cbc -K $encrypted_45d1b36fa803_key -iv $encrypted_45d1b36fa803_iv -in client-secret.json.enc -out client-secret.json -d
  # If the SDK is not already cached, download it and unpack it
  # - if [ ! -d ${HOME}/google-cloud-sdk ]; then
  #   curl https://sdk.cloud.google.com | bash;
  #  fi
  #- mkdir -p lib
  # Here we use the decrypted service account credentials to authenticate the command line tool
  # - gcloud auth activate-service-account --key-file client-secret.json

install:
  - gcloud config set project blissful-cell-141318

deploy:
  provider: gae
  keyfile: client-secret.json
  project: blissful-cell-141318
  config: src/main/appengine/app.yaml
  on:
    all_branches: true

